Group.create(name: 'Chest')
Group.create(name: 'Arm')
Group.create(name: 'Leg')
Group.create(name: 'Shoulder')
Group.create(name: 'Abs')

Exercise.create(name: 'Barbell Chest Bench', group_id: 1, approved:true)
Exercise.create(name: 'Dumbbell Chest Bench', group_id: 1, approved:true)
Exercise.create(name: 'Incline Barbell Bench', group_id: 1, approved:true)
Exercise.create(name: 'Incline Dumbbell Bench', group_id: 1, approved:true)
Exercise.create(name: 'Seated Machine Chest Press', group_id: 1, approved:true)
Exercise.create(name: 'Incline Bench Cable Fly', group_id: 1, approved:true)

Exercise.create(name: 'Hammer Curl', group_id: 2, approved:true)
Exercise.create(name: 'Dumbbell Biceps Curl', group_id: 2, approved:true)
Exercise.create(name: 'EZ Bar Curl', group_id: 2, approved:true)
Exercise.create(name: 'Tricep Extensions', group_id: 2, approved:true)
Exercise.create(name: 'Dumbbell Preacher Curl', group_id: 2, approved:true)
Exercise.create(name: 'EZ Bar Preacher Curl', group_id: 2, approved:true)
Exercise.create(name: 'Barbell Curl', group_id: 2, approved:true)
Exercise.create(name: 'Incline Dumbbell Curl', group_id: 2, approved:true)
Exercise.create(name: 'Incline Hammer Curl', group_id: 2, approved:true)
Exercise.create(name: 'Concentration Curl', group_id: 2, approved:true)
Exercise.create(name: 'Concentration Curl', group_id: 2, approved:true)

Exercise.create(name: 'Barbell Squat', group_id: 3, approved:true)
Exercise.create(name: 'Leg Press', group_id: 3, approved:true)
Exercise.create(name: 'Dumbbell Walking Lunge', group_id: 3, approved:true)
Exercise.create(name: 'Leg Extensions', group_id: 3, approved:true)
Exercise.create(name: 'Standing Calf Raises', group_id: 3, approved:true)
Exercise.create(name: 'Lying Leg Curl', group_id: 3, approved:true)
Exercise.create(name: 'Seated Leg Curl', group_id: 3, approved:true)

Exercise.create(name: 'Dumbbell Shoulder Press', group_id: 4, approved:true)
Exercise.create(name: 'Barbell Shoulder Press', group_id: 4, approved:true)
Exercise.create(name: 'Upright Barbell Row', group_id: 4, approved:true)
Exercise.create(name: 'Seated Bent-Over Rear Delt Raise', group_id: 4, approved:true)
Exercise.create(name: 'Side Lateral Raise', group_id: 4, approved:true)
Exercise.create(name: 'Military Press', group_id: 4, approved:true)
Exercise.create(name: 'Upright Cable Row', group_id: 4, approved:true)
Exercise.create(name: 'Upright Barbell Row', group_id: 4, approved:true)

Exercise.create(name: 'Decline Crunch', group_id: 5, approved:true)
Exercise.create(name: 'Ab Crunch Machine', group_id: 5, approved:true)
Exercise.create(name: 'Standing Rope Crunch', group_id: 5, approved:true)
Exercise.create(name: 'Reverse Crunch', group_id: 5, approved:true)
Exercise.create(name: 'Cross-Body Crunch', group_id: 5, approved:true)
Exercise.create(name: 'Toe Toucher', group_id: 5, approved:true)
Exercise.create(name: 'Russian Twist', group_id: 5, approved:true)
Exercise.create(name: 'V-Ups', group_id: 5, approved:true)


User.create(first_name: 'Billy', last_name: 'Hung', email:'billy7907@hotmail.com', password: '123')
User.create(first_name: 'Kevin', last_name: 'Love', email:'klove@gmail.com', password: '123')
